# Generated by Django 5.0.2 on 2024-02-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield9bcf', editable=False),
        ),
    ]
