# Generated by Django 5.0.2 on 2024-02-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_todo_title_todo_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default=None, max_length=24),
        ),
    ]
