# Generated by Django 5.0.2 on 2024-02-17 07:02

import class_view.web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(default=class_view.web.models.get_random_hash, max_length=24),
        ),
    ]
