# Generated by Django 5.0.1 on 2024-01-28 06:45

import django.db.models.deletion
import new_form.form1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0003_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=35, validators=[new_form.form1.models.non_empty_space]),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form1.department'),
        ),
    ]
