# Generated by Django 5.0.2 on 2024-02-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_person_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='prifile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
