# Generated by Django 5.0.2 on 2024-02-22 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profile_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
