# Generated by Django 5.0.2 on 2024-02-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_album_name_alter_album_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Pop Music', 'Pop'), ('Jazz Music', 'Jazz'), ('Rock Music', 'Rock'), ('Hip Hop Music', 'Hiphop'), ('R&B Music', 'Rnb'), ('Country Music', 'Country'), ('Dance Music', 'Dance'), ('Other', 'Other')], max_length=30, verbose_name='Genre'),
        ),
    ]
